### ISSUE TITLE
Will this work on mac os?

### ISSUE THREAD

**Issue by eladgel** [unfor19/install-aws-cli-action#10]

**Comment by unfor19** [comment]
Not supported since I haven't found a use case for running `aws cli` on any machine other than Linux.

To mix Linux and macOS builds, you can have one job with a Linux runner to do the `aws cli` calls, and on macOS job can consume the outputs of the Linux job.

If you need help with writing this kind of GitHub Actions Workflow, let me know and I'll comment with an example.

For now I'm keeping this issue open, I'll close it in a few days
